
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase is currently disconnected.
// To reconnect, go to the Supabase menu and connect your project.

const SUPABASE_URL = "";
const SUPABASE_PUBLISHABLE_KEY = "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || "https://example.com", SUPABASE_PUBLISHABLE_KEY || "example-key");
